### ISSUE TITLE
Add an option for using software OpenGL rendering

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#101]
In v3, I propose to add an option `soft_opengl=True` in `setup` command. If this option is `True` the software rendering libraries would be copied in the `host/lib` directory of the execution environment. In the container, this corresponds to `/casa/host/lib`. This directory would always be declared into `LD_LIBRARY_PATH`.

This way, the libraries would be located in a user editable directory even with singularity. It will be possible to remove or add them manually after the setup.

**Comment by ylep** [comment]
I would argue for an alternative approach: copy the software-only libGL in the system imagse, into a path that is *not* in the default library search path (e.g. `/casa/sw-only-libgl`). We can then optionally enable the library at runtime (during `casa_distro run`) by setting `LD_LIBRARY_PATH` using the `--env` option of Singularity/Docker.

As a reminder, see https://github.com/brainvisa/casa-distro/issues/59 and https://github.com/brainvisa/casa-distro/issues/100 for some issues that can be caused by the software-only libGL

**Comment by ylep** [comment]
Investigating the need for the software-only libGL and the transparent windows issue, I found that in the current Singularity casa-run and casa-dev images, the software-only libGL has already been abandoned. With this image, I did the following tests:

- On a machine with a NVidia GPU running Ubuntu 16.04 (standard CEA install), with `--nv` enabled, OpenGL works correctly as long as the `XAUTHORITY` environment variable is passed (which is ensured by casa-distro). If that environment variable is missing (e.g. running the container directly with `singularity --cleanenv`) OpenGL apps will crash (Segmentation fault).

- On the same machine, with `--no-nv`, OpenGL **does not work**. OpenGL apps give this error message: `libGL error: failed to load driver: swrast` (full message below). This appears even when setting the `LIBGL_ALWAYS_SOFTWARE=true` environment variable.

- On a laptop with an Intel graphics chipset running Ubuntu 16.04, OpenGL works correctly, both with hardware rendering (default) or software rendering (`LIBGL_ALWAYS_SOFTWARE=true`).

In other words, common use cases work, but we do not have a software-rendering fallback in case the proprietary NVidia drivers fail. I could not find out why the `swrast` driver is failing to load in the `--no-nv` case. Here is the full error log:

```
$ LIBGL_DEBUG=verbose glxgears
libGL: screen 0 does not appear to be DRI2 capable
libGL: MESA-LOADER: dlopen(/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  43
  Current serial number in output stream:  42
```

**Comment by ylep** [comment]
In light of the comment above, I think that we do not have a sufficient need for reintroducing the software-only libGL. Although having a software-rendering fallback would be nice, it should ideally be done using the mesa libs installed in the system of the container. Only if we do not manage to use these should we compile a software-only mesa.

Feel free to reopen this issue if you encounter a case where you critically need a software-rendering fallback.

**Comment by ylep** [comment]
Well, the need just appeared: we can use OpenGL on Mac OS under Singularity, but there is no alternative to software rendering there. The problem is that the system-provided mesa triggers the same `libGL error: failed to load driver: swrast` error as above.

So, we need to:
- Either find a way to get the system libGL to do software rendering;
- Or, reintroduce a specifically compiled software-only libGL. :frowning_face:

**Comment by ylep** [comment]
Following a suggestion of @sapetnioc (https://github.com/brainvisa/casa-distro/issues/113#issuecomment-688800551) I propose to have the following options for managing the OpenGL ~nightmare~:

- `opengl=auto` performs auto-detection: same as `nv` if an NVidia device is present, otherwise same as `container`, unless we detect a case where that is known to fail (in which case we would use `software`).

- `opengl=container` passes no special options to Singularity: the `mesa` installed in the container is used

- `opengl=nv` passes `--nv` to Singularity options (mounts the proprietary NVidia driver in the container)

- `opengl=software` sets `LD_LIBRARY_PATH` to use software-only OpenGL rendering.

**Comment by denisri** [comment]
I reopen #59 since it appears that we really must provide a working libGL.
