### ISSUE TITLE
Setting the base directory for the casa-distro repository

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#124]
The casa-distro repository is determined, in order of priority, by:

1. the `base_directory` supplied on the command-line (is this option available for all commands?)

2. ~the global `-r` option to `casa_distro`~ (removed in casa-distro 3)

3. the `CASA_DEFAULT_REPOSITORY` environment variable

4. PROPOSED: an option in a configuration file (maybe `~/.config/casa-distro/casa_distro_3.json`)

5. hard-coded `~/casa_distro`.

The config file would be useful to support users who cannot use their home directory (e.g. limited quota...)

**Comment by denisri** [comment]
document the `CASA_DEFAULT_REPOSITORY` env variable in the help

**Comment by sapetnioc** [comment]
Finally, are environment variables enough to change default options or do we need to introduce a configuration file as suggested here ?

In my opinion, it could be interesting to improve options management but it requires a bit of work. I would choose to postpone this feature to next release after the 3.0.

**Comment by sapetnioc** [comment]
Since each environment directory is now independent, we could replace the `base_directory` by a list of environment directories that would be stored in `~/.config/casa-distro/casa_distro_3.json`. Each new setup would add a new item to this list. Even if the setup is done in a container, this is possible because it uses default Singularity behavior and home dir is mounted in container.

Commands using several directories (`list`, `mrun`) would simply use this list instead of looking for a single directory. Hence, each environment could be anywhere on the file system.

**Comment by sapetnioc** [comment]
I added this issue to BrainVISA 5 release so that we take a decision on it before the release.

**Comment by denisri** [comment]
Is this ticket still relevant ? Or can we close it ?

**Comment by ylep** [comment]
Well, I still think the situation could be improved (i.e. in some cases we have to set `CASA_DEFAULT_REPOSITORY` environment variable whereas it could be detected automatically) but the formulation of this issue is probably not very relevant any more, so I agree to close it.
