### ISSUE TITLE
Decide where to put casa_distro_launcher

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#127]
Currently [casa_distro_launcher](https://github.com/brainvisa/casa-distro/blob/3.0/bin/casa_distro_launcher) is in the casa-distro repository, under `bin/`. This is not consistent because contrary to the rest of the casa-distro project, it is destined to be run inside of the container, not on the host. We discussed more logical places where it could live:

1. The brainvisa-cmake project
2. The soma-base project (because it has a dependency on `soma.qt_gui`)
3. The casa-distro project, but not under `bin`(maybe somewhere under `share`).

We have keep in mind that this tool needs to communicate with the casa-distro that runs on the host (i.e. it needs to write a configuration file for it), so we must take care that they stay compatible (we should probably write a mini-API spec) even when using an old version of the tool with a newer casa-distro (we cannot control the version of the launcher if it is installed in the image).

As a side issue, we currently have casa-distro in every build tree (the `standard` package set includes it), but in fact it is not needed in the container (except if we keep `casa_distro_launcher` under `bin`).

**Comment by denisri** [comment]
I'll start from the end to answer...
Casa-distro is installed in every build tree, yes, it doesn't seem necessary since casa-distro runs outside of the container, whereas it is installed inside of it. This has an advantage however, at least when the build tree is on a filesystem seen by the host machine (which is our normal workflow): we can pick casa-distro from its sources to run it from the host, which avoids the needs to have it installed elsewhere, and allows to keep it up-to-date when running bv_maker in the container. This can be discussed, of course.
The launcher needs to run inside the container to get its dependencies (you're right to point out that it also relies on soma-base), so I agree not to put it in `casa-dostro/bin/`. I still feel that it's closer to casa-distro than to brainvisa-cmake or even soma-base (both in spirit and logical/software links) so I would tend to keep it in casa-distro, but I don't have a very strong feeling about it.
Brainvisa-cmake is more developer-oriented when this launcher is for users. But even this may be discussed since bv_env is actually in brainvisa-cmake and also needed for users...
Soma-base is a very general library, not dedicated to a specific application or framework, and here we are really in a strong framework.
And the tool anyway needs knowledge of casa-distro and the container config.

**Comment by ylep** [comment]
:+1: to leave the launcher in casa-distro, but move it outside of `bin/`

We still have to decide how to install it into the container, though:

1. Use the casa-distro from `/casa/src/development/casa-distro/master`, and install it specifically from there (we need to special-case it if it does not live in `bin`)

2. Copy it from the casa-distro running on the host (e.g. store it under `share`) during `create_user_image`

**Comment by denisri** [comment]
I'd use 1. because it seems simpler to me. The `bv` script will take care of calling it the correct way inside the correct container.

**Comment by denisri** [comment]
I would put it in `share/scripts`, so that it gets installed in `/casa/install/share/casa-distro-3.0/scripts/casa_distro_launcher` in a user distribution.
