### ISSUE TITLE
Make sure that casa-distro works when installed with pip

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#131]

**Comment by sapetnioc** [comment]
Is it possible in PyPi to publish a realease that is not the default one ? We need to publish the 3.0 branch but just for testing.
If I remember well, there is a test PyPi server that could be the right option to perform tests.

**Comment by ylep** [comment]
Yes there is https://test.pypi.org/, but I already want to make sure that we can simply use `pip install .` from a local repository

**Comment by denisri** [comment]
By the way, is there a means to split the pip package into 2, user and developer parts ? I guess yes because I think pip supports a notion of optional modules. It would be nice to separate share/docker (plus the casa_distro_admin command) which contains 34 Mb of binary data, whereas the rest is just a few Kb. It's not a big problem anyway but it would be nicer to be minimal for users.

**Comment by ylep** [comment]
During `tox` tests (which run on Travis) the package is installed using its setup.py, so we can trust that it will work when installed via `pip` (insofar as tests are sufficiently complete... but I have added a few tests to check if the `share` directory is detected correctly).
