### ISSUE TITLE
Include basic graphical tools in the casa-run images

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#140]
Users will need basic graphical tools for doing common tasks in the containers:

- a terminal emulator (e.g. `lxterminal`) can be useful to run custom scripts, there will be a button in `casa_distro_launcher` to open one

- a text editor is needed e.g. for viewing transformation matrices, JSON files... with the Axon viewer. I suggest `leafpad`, which is minimalistic and lightweight.

- I hate to say it, because I want to keep the images as small as possible, but... do we need a web browser? Some software needs to display help, or quality control reports, or Jupyter notebooks... I do not have a specific use-case in mind right now, but it must exist, because there is a `htmlBrowser` config in Axon...

- There is also a `pngViewer` config in Axon, maybe we need a small image viewer like `gpicview`

**Comment by denisri** [comment]
I have also hesitations for the web browser. Axon can use the web engine of Qt to display docs, but I don't thing it can display notebooks or other advanced things (maybe I'm wrong).
I totally agree for the other needs.
Note that some config (axon) defaults / autodetect features should be adjusted to detect `leafpad` or `gpicview` because they're not in the list of classical tools it is looking for.

**Comment by sapetnioc** [comment]
In some tests I done in the past, the Qt Web Engine was able to display sites with Javascript. Therefore, unless a specific extension is used to display Notebooks, it should work.

**Comment by denisri** [comment]
Axon has been updated to detect these software programs.

**Comment by denisri** [comment]
Please also include `vim` (or `nano`) in the casa-run container... A non-GUI text editor is very useful when working remotely through ssh...

**Comment by denisri** [comment]
I need to rebuild images, so I'll do this ticket now to avoid having to rebuild them again later.
