### ISSUE TITLE
New 'bv-install' command for end users?

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#144]
Should we implement a new `bv-install` command for end users, doing the following:

- sheer `bv-install`: interactive prompt presenting the list of versions available on brainvisa.info, the version(s) that are currently installed, and proposing to install the latest version by default
- `bv-install download brainvisa-5.0` / `bv-install download brainvisa` (latest)
- `bv-install list`
- `bv-install remove brainvisa-5.0`

_Originally posted by @ylep in https://github.com/brainvisa/casa-distro/issues/119#issuecomment-689588443_

**Comment by sapetnioc** [comment]
In my opinion, this command will be the first to be launched by users when they install BrainVISA. Therefore we must define the installation procedure on the three systems (Linuw, Windows, Mac) in order to decide what should be the entrypoint of this command. I wonder if a module usable with something like `python -m bv.install` would make things easier for end users. If casa_distro is already installed in the default Python path it seems simpler than finding a `bv-install` command.

**Comment by sapetnioc** [comment]
To my opinion, we moved away from this `bv-install` command. The path of a user to download BrainVISA will look like that :

1. Go to the download section of BrainVISA web site and choose appropriate image (distro / version / container type)
2. Install Singularity or VirtualBox as explained on the web site
3. Download the image
4. For VirtualBox directly use the VM
5. 1. For Singularity setup a user environment :
   2. mkdir /somewhere/brainvisa
   3. singularity run -B /somewhere/brainvisa:/casa/setup /elsewhere/brainvisa-5.0.sif
   4. /somewhere/brainvisa/bin/brainvisa

**Comment by denisri** [comment]
I thought I understood from our last discussion that there could be both: a web download page + a very lightweight install script, which could list available images, and allow to choose an environment to perform the setup. Here I have in mind more developer environments than user environments, because they require user choices (branch, distro), but the "list images" feature is of interest in all cases.
Well, then, if we decide that the web page is enough, then we should close this ticket, and publish this download page somewhere quickly because right now users and developers have no entry point to setup an install.

**Comment by sapetnioc** [comment]
Such a help script would need to have access to the distro list. Therefore, since casa-distro is in all images, I was thinking to modify images entrypoints to run a casa_distro command in the container to get help. For instance running the image without any parameter nor any mount could show this help. We could also support an image parameter such as `help`, `--help` or `-h`.

For developers it is ok since they all need to download the same dev image anyway. For users, they must choose the image to download from the website before getting help. But, in that case there is no setup option (by now) and we may automatically launch the setup gui at the end of the setup, providing a possibility to be guided.

**Comment by ylep** [comment]
It seems that we agree on getting away from a `bv-install` command, so I will close this issue.
