### ISSUE TITLE
Debian package of Singularity 3.6 for Ubuntu 16.04 and Ubuntu 18.04

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#147]
We need to provide our local NeuroSpin users with an easy way to install Singularity, ideally have it installed by default by the sysadmins (_infogérant_). Having a `.deb` package is a first step in that direction.

**Comment by denisri** [comment]
That would be great, even for external users. We must realize that the casa-distro distribution is not only a software package to install (what it used to be until now) but needs to install python (on linux/mac machines it is part of the system), singularity, then casa-distro. This is not so obvious for non-comuter scientists, and installing singularity from sources implies also to have development tools installed, compile and build the go language, maybe handle disk size problems (I ran into such problems because go installs hundreds of MB of libraries in `~/go` without telling you) so this may become very tricky in some situations.

**Comment by ylep** [comment]
@nsouedet suggested the following recipe to quickly build a package:

```shell
sudo apt install build-essential uuid-dev squashfs-tools libseccomp-dev wget pkg-config git libcryptsetup-dev elfutils rpm alien
pushd /tmp
git clone https://github.com/hpcng/singularity.git
pushd singularity
git checkout v3.6.2
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" ./mconfig
make -C builddir dist
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" rpmbuild -tb  --nodeps singularity-3.6.2.tar.gz
sudo alien --to-deb --scripts /home/a-far-mc-service/rpmbuild/RPMS/x86_64/singularity-3.6.2-1.x86_64.rpm
```

**Comment by sapetnioc** [comment]
A version of the script modified to select Singularity version and that works in `docker run -it --rm ubuntu:18.04` (also tested with Ubuntu 20.04) :
```
# There is no sudo in Docker. For using sudo, set SUDO=sudo
SUDO=
SINGULARITY_VERSION=3.6.4
apt update
$SUDO apt install build-essential uuid-dev squashfs-tools libseccomp-dev wget pkg-config git libcryptsetup-dev elfutils rpm alien
pushd /tmp
export VERSION=1.13 OS=linux ARCH=amd64 && \
  wget https://dl.google.com/go/go$VERSION.$OS-$ARCH.tar.gz && \
  $SUDO tar -C /usr/local -xzvf go$VERSION.$OS-$ARCH.tar.gz && \
  rm go$VERSION.$OS-$ARCH.tar.gz
export PATH=/usr/local/go/bin:$PATH
git clone https://github.com/hpcng/singularity.git
pushd singularity
git checkout v${SINGULARITY_VERSION}
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" ./mconfig
make -C builddir dist
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" rpmbuild -tb  --nodeps singularity-${SINGULARITY_VERSION}.tar.gz
$SUDO alien --to-deb --scripts $HOME/rpmbuild/RPMS/x86_64/singularity-${SINGULARITY_VERSION}-1.x86_64.rpm

# Checking deb package
dpkg -i singularity_3.6.4-2_amd64.deb
singularity --version
 ```

**Comment by sapetnioc** [comment]
I wrote two scripts using Docker to automatically build the debian packages for three Ubuntu versions: 16.04, 18.04 and 20.04. There is a trick to have the final file not written as root but with current user uid (necessary for some shared file systems). There is a env var substitution in `build_all.bash` that requires bash but an sh version can be done if necessary.

I successfully installed the 16.04 version on my Neurospin machine. I had to remove `singularity-container` first.

Here is `build_all.bash`
```#!/bin/bash

SINGULARITY_VERSION=3.6.4
GO_VERSION=1.13
SYSTEMS="ubuntu-16.04 ubuntu-18.04 ubuntu-20.04"

for system in $SYSTEMS; do
    docker run --rm \
      --env SYSTEM=${system} \
      --env UID=$UID \
      --env GO_VERSION=$GO_VERSION \
      --env SINGULARITY_VERSION=$SINGULARITY_VERSION \
      -v $PWD:/host \
      ${system/-/:} \
      sh /host/build.sh
done
```

And `build.sh`:
```
set -xe

echo $SYSTEM
useradd --no-create-home --uid $UID host_user

apt update -y
$SUDO apt install -y build-essential uuid-dev squashfs-tools libseccomp-dev wget pkg-config git libcryptsetup-dev elfutils rpm alien
export OS=linux ARCH=amd64
wget https://dl.google.com/go/go$GO_VERSION.$OS-$ARCH.tar.gz
tar -C /usr/local -xzvf go$GO_VERSION.$OS-$ARCH.tar.gz
rm go$GO_VERSION.$OS-$ARCH.tar.gz
export PATH=/usr/local/go/bin:$PATH
git clone https://github.com/hpcng/singularity.git
cd singularity
git checkout v${SINGULARITY_VERSION}
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" ./mconfig
make -C builddir dist
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" rpmbuild -tb  --nodeps singularity-${SINGULARITY_VERSION}.tar.gz
$SUDO alien --to-deb --scripts $HOME/rpmbuild/RPMS/x86_64/singularity-${SINGULARITY_VERSION}-1.x86_64.rpm

chown host_user singularity*.deb
cp singularity*.deb /host/singularity-$SYSTEM-x86_64.deb
```

**Comment by sapetnioc** [comment]
In `build.sh`, there is a problem for Ubuntu 20.04 during `apt install ...`. The package `tzdata` is installed and configured. This trigger an interactive dialog using Readline that make stuck the whole process. Some options must be added to `apt install`.

**Comment by sapetnioc** [comment]
The new `build.sh`. Are we putting these two files in casa-distro sources ?

```
set -xe

echo $SYSTEM
useradd --no-create-home --uid $UID host_user

apt update -y
DEBIAN_FRONTEND=noninteractive apt install -y build-essential uuid-dev squashfs-tools libseccomp-dev wget pkg-config git libcryptsetup-dev elfutils rpm alien
export OS=linux ARCH=amd64
wget https://dl.google.com/go/go$GO_VERSION.$OS-$ARCH.tar.gz
tar -C /usr/local -xzvf go$GO_VERSION.$OS-$ARCH.tar.gz
rm go$GO_VERSION.$OS-$ARCH.tar.gz
export PATH=/usr/local/go/bin:$PATH
git clone https://github.com/hpcng/singularity.git
cd singularity
git checkout v${SINGULARITY_VERSION}
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" ./mconfig
make -C builddir dist
PATH=/tmp/go/bin:${PATH} GOPATH="/tmp/.go/cache" rpmbuild -tb  --nodeps singularity-${SINGULARITY_VERSION}.tar.gz
$SUDO alien --to-deb --scripts $HOME/rpmbuild/RPMS/x86_64/singularity-${SINGULARITY_VERSION}-1.x86_64.rpm

chown host_user singularity*.deb
cp singularity*.deb /host/singularity-$SYSTEM-x86_64.deb
```

**Comment by denisri** [comment]
> Shoul we put these two files in casa-distro sources ?

I'd say: yes...

**Comment by sapetnioc** [comment]
I wonder if it would not be more consistent with the rest of the project to use Singularity instead of Docker to build the debs. We could add a `casa_distro_admin create_debs` command to create/publish the packages without requesting a Docker dependency. I did it with Docker because it was simpler to start interactively.

**Comment by denisri** [comment]
Not sure of that - it would require to install a first `singularity` in order to install a second one... Maybe both may be useful if it's not too difficult to maintain ?
Other question: if we build these packages for some linux distributions (ubuntu 16/18/20?), do we publish them anywhere (and where) or do we leave it to users to use your script to build the packages on their own ?

**Comment by sapetnioc** [comment]
We should publish them. The goal is to allow users to install singularity easily. If they manage to install Docker and use my scripts to generate a deb that they finally install, I think they are skilled enough to directly install Singularity from sources. 
If we publish, users will only have to download a file and install it either with `dpkg -i` or graphically.

**Comment by sapetnioc** [comment]
In my opinion, no standard user will never generate a deb for Singularity. Only BrainVISA admin (or advanced users) with an already working casa-distro will do that. This is why I wonder if we should rely on Singularity for that. But I am not sure because there is this bug in  `singularity pull` preventing to use `--disable-cache` that makes things complicated (there is a cache for root and another cache for each user).
