### ISSUE TITLE
bv_maker not in path for new dev environment

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#158]
To reproduce:

```
casa_distro setup_dev distro=brainvisa branch=master name=bidon
casa_distro bv_maker name=bidon
```

**Comment by sapetnioc** [comment]
Should we add `/casa/brainvisa-cmake/bin`  to `PATH` in `dev_environment.sh` ? Or is there a possible side effect ?

**Comment by sapetnioc** [comment]
Other error related to a change in dev image environment. `bv_maker` cannot find `bv_maker.cfg`:
```
$ casa_distro run name=bidon /casa/brainvisa-cmake/bin/bv_maker
Configuration file: None

bv_maker summary:
All went good.
```

**Comment by denisri** [comment]
My fault...
I made an error while working on #114, and I did push the changes because I had to build images on my home machine instead of the laptop I'm currently working on (because upload time for an image is 1min30 there and maybe 10 hours here). It's fixed in principle (I'm retreiving the new dev image to finish testing)

**Comment by sapetnioc** [comment]
Good to know while I am still in Neurospin with a fast network to pull
image.
