### ISSUE TITLE
Make bv become a symlink in dev environment 

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#180]
When creating a new development environment, bv command is copied from casa-distro. But once casa-distro source are available, it is best to use bv command located there to allow modification, tests and submission

Bv command could check the existence of casa-distro sources directory and replace the script by a symlink.

**Comment by denisri** [comment]
Does it have to be checked / updated at each run ?
In addition, symlinks to all commands in `/casa/build/bin` should also be made (or updated). I had a script doing all this (`share/scripts/share/scripts/casa_build_host_links`) unless you have already re-done something similar in `bv`.
About the question: when to update:
- if `bv` does it each time it is run, things will be automatically updated "often", but not within a container session (I usually use `casa_distro shell` and keep the shell open several days/weeks...)
- thus I would appreciate having a way to call it (even manually) from within a running container, if possible [optional]
- `bv` may be called very often because it's the wrapper for every commandline, and may be called from large pipelines and workflows. So the lighter it is, the better. Checking hundreds of symlinks to hundreds of commandlines every time is maybe a significant overhead (?)

**Comment by denisri** [comment]
it's done within bv_maker build.
