### ISSUE TITLE
casa-distro should not be installed in casa-run images, but in casa-dev and user images

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#207]
The problem with casa-distro being installed in the `casa-run` images is that whenever casa-distro is updated, we need to rebuild the whole suite of images (`casa-run` and `casa-dev`), which takes a long time.

I think it would be better to set up the `/casa/casa-distro` directory during construction of `casa-dev` images and user images

**Comment by sapetnioc** [comment]
We do not need it in run images. There is an ìnstall_casa_distro` method on image builders (RecipeBuilder and soon on VBoxMachine). But creation of user image does not use a builder. Therefore we must take care to make something compatible with VirtualBox. It may be a good idea to use a builder for user image too in order to reuse the same code.
