### ISSUE TITLE
how does casa-distro work now ?

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#210]
I think I'm totally lost in casa-distro suddenly...

* `casa_distro setup_user` and `casa_distro setup_dev` don't work any longer. They seem to be meant to be used from within the container, now (with an install path in `/casa/setup`). But the "host" commands still exist. ?
* we can install using `singularity -B /path:/casa/setup image.sif`, yes, but the `casa_distro` command was handy when managing multiple environments (especially from the same dev image), avoiding to specify all paths. Or will the `casa_distro` command totally disappear ? (I didn't understand this was the plan)
* After a `setup_dev` from a dev image, casa-distro modules are not available in the image through paths. Thus the `configuration_gui` does not work any longer. This is probably related to #209 (and of course #80). Is it intentional ?

We really really need to clarify what parts of casa-distro needs to run on host side and what needs to run on container side, what needs to be installed in images, and how we use them

**Comment by ylep** [comment]
Agreed, we need to clarify all that. Here are a few answers from the point of view of my workflow:

- Yes the `setup_user` and `setup_dev` commands are ambiguous now, they work when run from inside the container with `/casa/setup`, I do not know if they still work from the host. If they do not, they should disappear from `casa_distro`. Or maybe there should be host versions of these commands that call `singularity run -B ...:/casa/setup`? I do not find this super useful for myself, but we could still implement it if you find it useful.

- After a `setup_dev` the configuration GUI does not work, but I think this is okay because we expect developers to compile first, before using the software... But in that case it would be nice to display a usage message telling to run bv_maker first. This is definitely related to #209, I propose to continue the discussion there.

**Comment by denisri** [comment]
* `setup_user` and `setup_dev`: I found these commands quite useful, since I often try installing new environments, and respect the base_directory/environment organization, so these comamands avoid to specify paths for images and environments at each run, avoid to create the new environment directory, and also allow to download new images if I remember. Not that they are absolutely mandatory, but I find them useful. Making them call `singularity run ...` would be a kind of mess since this `singularity run ...` command already calls `casa_distro setup_something`, it would be a call loop ;) but we could detect if we are inside a container, and if yes, then this is the "unusual case" when called from within a `singularity run` setup operation (and honestly I think that from within a container the setup should call other functions than casa_distro user commands, which are normally called from the host). But the former code has maybe already disappeared ?
* The GUI is normally what users call first after a setup, so I imagine it would be nice if it works at least minimally in a new dev environment. Or at least we must print something "nice" to the user, because right now it just leaves the user with the impression that the tools don't work at all. I can take care of this.

**Comment by ylep** [comment]
> and honestly I think that from within a container the setup should call other functions than casa_distro user commands, which are normally called from the host

I totally agree with this, see what I just proposed in https://github.com/brainvisa/casa-distro/issues/209#issuecomment-760109172
