### ISSUE TITLE
Update Singularity

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [brainvisa/casa-distro#271]
The current version appears to be [3.7.0](https://github.com/brainvisa/casa-distro/blob/24f70b0/python/casa_distro/admin_commands.py#L56).

Because of [CVE-2021-32635](https://github.com/hpcng/singularity/security/advisories/GHSA-jq42-hfch-42f3), we must update to a more recent version, either [3.7.4](https://github.com/hpcng/singularity/releases/tag/v3.7.4) or the more recent 3.8 series (current version is [3.8.2](https://github.com/hpcng/singularity/releases/tag/v3.8.2)).

**Comment by DimitriPapadopoulos** [comment]
Perhaps update to a more recent version of Go too, such as [1.16.4](https://github.com/hpcng/singularity/commit/6da1255), or perhaps [the last of the 1.16 series which is 1.16.7 or the latest 1.17](https://golang.org/dl/).

**Comment by sapetnioc** [comment]
Thanks Dimitri. I will raise the attention of BrainVISA team to this ticket and make new packages with latest versions (and remove other ones) unless someone identify a potential problem.

**Comment by sapetnioc** [comment]
Other question, there was [a change in the Singularity package names starting since 3.8 version](https://github.com/sylabs/singularity/releases/tag/v3.8.0). Should we rename our packages `singularity-ce` ?

**Comment by sapetnioc** [comment]
We are currently using the hpcgn repository in our package building system. This is not a real choice, just a copy of an initial recipe found by @nsouedet . The `casa_distro_admin singularity_deb` command is not working with 3.8.2 version. This could be due to a modification of package naming. I propose to update it in an incompatible way (impossible to build old releases without reverting to an older version of casa_distro).

**Comment by ylep** [comment]
> Should we rename our packages `singularity-ce` ?

If we *do* choose to rename, we have to add a `Conflicts: singularity-container` and `Replaces: singularity-container` dependency, because our package would most probably not support being installed at the same time as that version from the Debian/Neurodebian repositories. This is the reason why we switched the name from `singularity` to `singularity-container` a few months ago (https://github.com/brainvisa/casa-distro/issues/184).

**Comment by DimitriPapadopoulos** [comment]
The package name `singularity` had already been taken by the game Singularity ([singularity/singularity](https://github.com/singularity/singularity/)), hence the different package name `singularity-container`. We can keep `singularity-container` as long as we stay with the current [hpcng/singularity](https://github.com/hpcng/singularity).

Package names should be:
[hpcng/singularity](https://github.com/hpcng/singularity) →`singularity-container`
[sylabs/singularity](https://github.com/sylabs/singularity) →`singularity-ce` or `singularityce-container`

Perhaps we can keep [hpcng/singularity](https://github.com/hpcng/singularity) and`singularity-container` in the short term. Some [sylabs/singularity](https://github.com/sylabs/singularity) packages may come up later on.

That said, we agree about `Conflicts: singularity-container` and `Replaces: singularity-container`.

**Comment by DimitriPapadopoulos** [comment]
Suggested name for SingularityCE RPM packages is [`singularity-ce`](https://sylabs.io/guides/3.8/admin-guide/installation.html#build-and-install-an-rpm).

But then, the previously suggested name for Singularity RPM packages was plain [`singularity`](https://sylabs.io/guides/3.7/admin-guide/installation.html#build-and-install-an-rpm), which for DEB packages conflicts with the game.

**Comment by denisri** [comment]
I agree with all that, but for us the first question is: are all these new versions of singularity working the same way, and are they working well with our brainvisa distributions ? Once tested we can finalize the "official" package name and version.

**Comment by sapetnioc** [comment]
I finally choosed singularity-ce for the following reasons:
- The repository seems to have been more active these last days
- This is @DimitriPapadopoulos's proposal
- There is a clear and explicit package name

I am trying the ubuntu-18.04 version 3.8.3 (Go 1.17) for a while before subitting.

Do anyone know how to add the dependencies suggested by @ylep ?

**Comment by ylep** [comment]
> Do anyone know how to add the dependencies suggested by @ylep ?

Not straightforward with our `alien`-based packaging, here is a recipe that might work: https://alnahian.wordpress.com/2008/09/16/putting-debian-dependency-while-creating-deb-by-alien/

Eventually we should move away from `alien` toward a better packaging method, @DimitriPapadopoulos maybe the Gipsi has a better way to create the packages?

**Comment by ylep** [comment]
@sapetnioc I found the Gipsi package (http://alambic.intra.cea.fr/distrib/ubuntu/pool/main/s/singularity-container/singularity-container_3.8.0~ubuntu20.04-1_amd64.deb) but not the recipe they used for building it, I will ask them.

**Comment by DimitriPapadopoulos** [comment]
Yes, having the same package as Gipsi would be great. Additionally, they have a single DEB package for all distributions. Much easier.

**Comment by ylep** [comment]
Taking inspiration from the Gipsi packaging script (thanks to them!), as well as the official Debian package (which we cannot use as-is, because it is only available for Debian _unstable_, depends on Go being packaged, and is lagging at version 3.5.2), I have tried to combine the best of both worlds and here is the resulting script: https://gist.github.com/ylep/35fb71d0f3d9ee8bcc6fefecde5ef682.

There is no more RPM package conversion involved, and the resulting package should be quite clean from the Debian point of view (the only issues that `lintian` reports are related to missing files required by the Debian policy).

@DimitriPapadopoulos unfortunately I don't think we can confidently distribute a single package to suit multiple releases of Ubuntu, because there may be incompatibilities in the dependencies.

**Comment by DimitriPapadopoulos** [comment]
Oh, there could be incompatibilities, but there are most probably none. The single Gipsi package appears to be compatible with lots of distributions. You just need to build the package on the oldest supported OS.

**Comment by sapetnioc** [comment]
The new building script is not compatible with Ubuntu 16.04. There is, at least a dev package that cannot be installed. I propose to almost drop support to Ubuntu 16.04. We would keep `singularity-container-3.7.0-ubuntu-16.04.deb` package on BrainVISA web site remove all other packages in favor of a more recent release of `singularity-ce`.

**Comment by denisri** [comment]
OK for me.

**Comment by sapetnioc** [comment]
FYI, another Docker and docker-compose compatible tech : https://github.com/containerd/nerdctl
The other one I heard about is https://podman.io/
They both claim to support rootless (Docker also, it is true but setup really not easy). We may have to investigate further if Singularity fork weaken the project.
