### ISSUE TITLE
outdated vbox dev image

### ISSUE THREAD

**Issue by denisri** [brainvisa/casa-distro#272]
The casa-dev image for VirtualBox is totally outated (march 2020) and is not functional:
* `bv_maker` is not available in the path
* `/casa/dev_environment.sh` points paths to `/casa/host/bootstrap` which does not exist (`/casa/bootstrap` does exist)
* `/casa/dev_environment.sh` points dev variables to /`casa/host` which does not exist
* The docs in https://brainvisa.info/web/download.html says to edit configs in `/casa/conf/bv_maker.cfg` which does not exist
* the image does not include libraries included more recently

Singularity images have been updated several times (last is currently june 30 2021, `casa-dev-5.0-4.sif`), but vbox ones have not. As singularity is not available easily (or not at all) on non-linux systems, the vbox variant is the only choice for now, so we need to fix and update it.

**Comment by sapetnioc** [comment]
We do not have dev image for VirtualBox anymore. It is not necessary to develop in Windows because it is far better to use WSL2 and work as under Linux (this is what I do when I am on Windows). For Mac developers I do not know any alternative. However, I suggest to close this issue as "not planned" and to wait for someone asking how to develop with BrainVISA on Mac.
