### ISSUE TITLE
Remove the svn wrapper from casa-dev images

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#31]
The `svn` wrapper script adds `--noninteractive`, which makes it impossible to use an editor or a mergetool from within the container.

If we remove it, we have to find a solution for handling the password save without user interaction.

**Comment by sapetnioc** [comment]
The problem is that the desired level of interactions depends on the context. For open source distro, we need to use a login and password for BioProj but we do not want interactions. But for all other login/passwords, it would be better to use existing solutions as you suggest.

To solve the issue, we may change the wrapper to be transparent (i.e. directly call `/usr/bin/svn` without adding parameters) if the file `svn.secret` does not exist.

**Comment by sapetnioc** [comment]
Does anybody plan to work on that issue ?

**Comment by denisri** [comment]
I don't remember why -noninteractive` neeed to be passed to svn ?

**Comment by sapetnioc** [comment]
Otherwise it asks for a password

Le lun. 21 sept. 2020 à 16:06, Denis Rivière <notifications@github.com> a
écrit :

**Comment by denisri** [comment]
Even when we provide them through the commandline ? Crap...

**Comment by denisri** [comment]
It doesn't seem to ask for a password, at least not everytime. Maybe in some specific conditions ? But which ones...?

**Comment by denisri** [comment]
I have seen that also:
https://unix.stackexchange.com/questions/191048/how-to-make-svn-save-credentials-when-non-interactive
especially the 2 lines:
```
rm -fr ~/.subversion
yes yes | svn --username=user --password=guest ls svn://server/repo &>/dev/null
```

**Comment by denisri** [comment]
The above trick doesn't work since svn is using a graphical wallet application which asks things.
Maybe the best is to do as Yann says:

> To solve the issue, we may change the wrapper to be transparent (i.e. directly call /usr/bin/svn without adding parameters) if the file svn.secret does not exist.
