### ISSUE TITLE
Create the casa-run-5.3 VirtualBox image

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#326]
We urgently need to create the `casa-run-5.3.ova` image and test it if we want to be able to make a virtualized release of BrainVISA 5.1.0 on Friday!

Unfortunately I will not have time to do it until at least Thursday. Can somebody in @brainvisa/admin give it a try before that? Otherwise I will try on Thursday.

**Comment by sapetnioc** [comment]
I am trying to create these VirtualBox images.

**Comment by sapetnioc** [comment]
First step : casa-system-5.3.ova image is [there](https://brainvisa.info/download/).

**Comment by sapetnioc** [comment]
Done for casa-run-5.3.ova.

FYI: it was not possible to create the images from Neurospin because `apt update` and `apt upgrade` in the virtual machine had been either very very slow of simply failing to contact repositories (tried in France and USA). It was working very well outside the VM. Years ago, I already encountered unbelievable but reproducible problems with `apt` within a container but only from Neurospin: `apt upgrade` was failing at the hundredth package installation.
