### ISSUE TITLE
Update projects and release versions for the release of BrainVISA 5.0

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#82]
We decided on the following for the release (see below for the discussion that led to this workflow):

Get rid of *integration* branches (this is not part of the release plan proper, progress is tracked on https://github.com/orgs/brainvisa/projects/6)
- merge all integration into master branches
- delete integration branches

When we are ready for release,

- create numbered branches from *master* (e.g. *5.0*)
- Edit [components_definition.py](https://github.com/brainvisa/brainvisa-cmake/blob/master/python/brainvisa/maker/components_definition.py) to make the `release_candidate` “tag” point to the new numbered branches

When the RC is OK:

- create tags (e.g. *v5.0.0*) from the tip of the numbered branches
- Edit [components_definition.py](https://github.com/brainvisa/brainvisa-cmake/blob/master/python/brainvisa/maker/components_definition.py) to make the `latest_release` “tag” point to the tags just created

**Comment by denisri** [comment]
What should we do for branches management ?
- do all manually ?
- restore the casa_distro_admin create_release_plan command, maybe in a different program or different project ? This subcommand has simply disappeared in casa-distro 3...
- modify bv_release ? (it was not dealing with git)

More specifically for BV 5.0 what needs to be done ? I don't remember how we were supposed to handle branches in git... This is an attempt, correct me if I'm wrong:
- check that master and integration branches have different release numbers, unless they are identical. If not OK, set a new release number
- merge all master into integration branches
- move all master branches to numbers, or use tags (4.6.2) to save the current master [optional ? - 4.6.2 will never be released]
- move all integration to master branches
- re-create integration branches [optional, we could wait until real code has to be pushed there]

Then when we are ready for release,
- create release_candidate branches from master

When the RC is OK:
- create numbered branches or tags (4.7.0) from release_candidate
- create latest_release branch/tag from it

Note that "move" operations will break the continuity in git history. I think we had discussed this workflow and had a solution but I don't remember, it was years ago...

**Comment by ylep** [comment]
This also poses the question: as we are going to release a new major version, should we base the release on the current *integration* branches instead of *master*? That would mean, instead of what you proposed:

1. Merging *integration* into *master*
2. Deleting the *integration* branch (I recall that we discussed dropping it, in favor of doing feature-branches and merging them frenquently into *master*)

We should first do a big "diff" to see if there is a big risk of bringing disruptive changes from *integration*...

**Comment by denisri** [comment]
That's another way of doing it. I was talking about "move master to numbers" then "move integration to master", which would result in the same state at the end, except that:
- in your way branches history continuity would not be broken because the master branch continues to live
- but the merge integration -> master may be painful in some projects

> We should first do a big "diff" to see if there is a big risk of bringing disruptive changes from integration...

Yes but that's a big work...
In some projects there _are_ disruptive changes in `integration`: for instance in `pyaims`, the new numpy bindings to C++ arrays allow to bind array-like objects (RGB, AimsVector...) as additional dimensions, which changes significantly the way we use them. That's the most sensible change I have in mind, but there might be others.

**Comment by sapetnioc** [comment]
In my opinion, we should not use the integration branch. It's just a
particular feature branch that was getting hard to merge because we
couldn't do multiple branches with Subversion. It's special because it's
made to contain changes that take a very long time to develop and we need a
common branch between different independent projects to globally test
features under development. So, the integration branch is just a place
where we can merge all the ongoing feature branches. By definition, it is
never ready for release.

**Comment by denisri** [comment]
OK then, it suits me ;)
So the new workflow would look like:

- cretae numbered branches / tags from the current master branches [optional ? - 4.6.2 will never be released]
- merge all integration into master branches
- delete integration branches

Then when we are ready for release,

- create release_candidate branches from master

When the RC is OK:

- create numbered branches or tags (4.7.0) from release_candidate
- create latest_release branch/tag from it

(looks simpler than my first attempt ;) )

**Comment by ylep** [comment]
I would argue for one more (big) change to the workflow proposed by Denis:

When we are ready for release,

- create numbered branches from *master* (e.g. *5.0*)
- Edit [components_definition.py](https://github.com/brainvisa/brainvisa-cmake/blob/master/python/brainvisa/maker/components_definition.py) to make the `release_candidate` “tag” point to the new numbered branches

When the RC is OK:

- create tags (e.g. *v5.0.0*) from the tip of the numbered branches
- Edit [components_definition.py](https://github.com/brainvisa/brainvisa-cmake/blob/master/python/brainvisa/maker/components_definition.py) to make the `latest_release` “tag” point to the tags just created

That approach would have several advantages:
1. avoid having a `release_candidate` or `latest_release` branch under version control, which are not very Git-friendly because:
    - a tag must never move, so we cannot make it a tag (although you *can* technically move a tag, clones will keep the old one unless you force the update with a very specific `git fetch` command)
    - a branch that jumps from version to version with force-pushes does not seem right to me...
2. we can quickly make a hotfix release (e.g. 5.0.1) if serious problems appear, by making a few commits on top of the numbered branches and repeating the last 2 steps.

**Comment by denisri** [comment]
I agree.

**Comment by denisri** [comment]
`trunk` / `integration` branches have been merged. `integration` branches have been removed. svn `trunk` have been left as they are but` components_definition.py` points to `bug_fix` branches. Version numbers have been set to 5.0.0.
When we are ready we can build `5.0` branches.
