### ISSUE TITLE
Perform tests on Mac for various Workflows

### ISSUE THREAD

**Issue by sapetnioc** [brainvisa/casa-distro#86]

**Comment by denisri** [comment]
It works more or less on Mac, but singularity has strange behaviours:
* sometimes / on some accounts containers become "silent" (singularity returns with no message), even on simplest containers like library://godlovedc/funny/lolcow (today lolcow is silent on our test account, whereas brainvisa-5.0-test2 works OK...)
* singularity doesn't seem to honor `--home` option even if it is actiually present in singularity
* singularity doesn't seem to pass any env variable at all, `SINGULARITYENV_something` are not set in the container

Thus many options and customizations we do through these are not taken into account, including X/GL setup. It has to be done manually inside the container, at each run.

Maybe I missed something somewhere... ?

Apart from this, casa-distro and containers seem OK. I have not run tests yet.

**Comment by denisri** [comment]
We have several options for Mac support with singularity:
1. drop Mac support. A bit a pitty considering the efforts already done and the "almost working" state...
2. wait for a newer version of singularity, but the beta is more than one year old (august 2019) and there has been no update and no news at all since then.
3. try to bidouille in the meantime. it seems difficult to pass information to the container, except through mount points (which are hopefully working). We could maybe write a temporary script when starting the container, mount it in `/casa/mac_bidouille` or anything, and in the container entrypoint, check if this directory/script exists and source it if it is ? The script would contain all env variables definitions and other needed things.

**Comment by sapetnioc** [comment]
For users, I am in favor of 1 with VirtualBox as only supported possibility. Today I would say the same for Windows too because I installed an Ubuntu with WSL2 on a new Windows machine this week-end and, to my opinion, is a bit too complicated for many users.

**Comment by sapetnioc** [comment]
I do not know what to say about developers on Mac. But since we do not have enough time to create and test a Mac specific solution, I would first try to use a dev image with VirutalBox too.

**Comment by sapetnioc** [comment]
We will probably get back to it later. But if we want to have a chance to release something quickly, I am afraid we should focus on VirtualBox for Windows and Mac.

I made a single issue for testing the VM on various systems : #141

**Comment by denisri** [comment]
That's why I left it in another branch, not in 3.0

**Comment by denisri** [comment]
Another issue for Mac with singularity in dev mode: svn doesn't work on Mac filesystems.
From the container (linux) on the host (mac) filesystem in /casa/src:
```
svnadmin create .repository
svnadmin: E000001: Can't open file '.repository/db/revs/0/0': Operation not permitted
svnadmin: E200042: Additional errors:
svnadmin: E000020: Can't open directory '.repository/hooks/post-lock.tmpl': Not a directory
```
and this is not a good news...

**Comment by denisri** [comment]
It's also not working on a NFS filesystem. Git is also not working. The client filesystem API on macs do not suit some operations performed by svn or git (file locking...?)
This way it seems almost impossible to develop on a mac through singularity. :( (at least this version of singularity ?)
I'm more optimistic for the user case.

**Comment by denisri** [comment]
I have setup the workaround for Mac. It's working. Thus the best option for a user who just wants to run the programs on Mac is probably singularity.
