### ISSUE TITLE
User-specific configuration in v3.0

### ISSUE THREAD

**Issue by ylep** [brainvisa/casa-distro#98]
The user-specific configuration introduced in master (v2.0) in https://github.com/brainvisa/casa-distro/pull/93 is not straightforward to merge into v3.0. I have done the merge and resolved the conflicts, but not yet reintroduced the feature in v3.0, because:

- configuration keys that used to be at the top-level are now in `configs`/`default`, I am not sure how we should merge the configs from the user-specific configuration files. In particular, if we want to define mount points in `~/.config/casa-distro/casa_distro.json`, it would be good if they applied to all the configurations, not only `default`.

@sapetnioc we can discuss the best way to implement this, and I can contribute once we reach a decision

**Comment by sapetnioc** [comment]
After a discussion with @ylep ,we decided the following rules to handle configuration in v3.0 :

- During the setup step, a `casa_distro.json` config file is created. It can contain values for some parameters used for running programs. In this case, these values replaces the hardcoded default values (when no value is given on command line). But the command line value has the priority on the final parameter value.
- At run time, the configuration is initialized with `host/conf/casa_distro.json` located in the execution environment directory. Then the configuration is updated with `$HOME/.config/casa-distro/<environment specific dir>/casa_distro.json`. Then it is updated with `$HOME/.config/casa_distro_3.json`. Finally, command line parameters can modify configuration.
- `<environment specific dir>` is still to be defined. We need it to be unique for any environment configured but we also would like that it is as short as possible and meaningful for user. Because users may have to navigatein that directories.
- The `verbose=yes` option must display the various configuration files used as well as the final configuration.
- Configuration should be as independent from container type as possible. Therefore, VirtualBox specific values such as `memory` and `disk_size` should not go in configuration.

**Comment by ylep** [comment]
> * At run time, the configuration is initialized with `host/conf/casa_distro.json` located in the execution environment directory. Then the configuration is updated with `$HOME/.config/casa-distro/<environment specific dir>/casa_distro.json`. Then it is updated with `$HOME/.config/casa_distro_3.json`. Finally, command line parameters can modify configuration.

@sapetnioc I thought that you wanted to get rid of the environment-specific user config? I am okay to keep it, but we should load it *after* `$HOME/.config/casa_distro_3.json`, so that the environment-specific user configuration overrides the generic user configuration. Also, I suggest that we name it `$HOME/.config/casa-distro/<environment specific dir>/casa_distro_3.json`  (with `_3`) for consistency.

**Comment by sapetnioc** [comment]
You are right, I misunderstood my notes. Let's forget about it. It will be very easy to put it back (a simple string to add in the code) if we discover a use case.
